spring.config.import=optional:file:.env[.properties]
spring.application.name=appointment

spring.datasource.url=${LOCAL_DB_POSTGRESQL_URL}
spring.datasource.username=${LOCAL_DB_POSTGRESQL_USERNAME}
spring.datasource.password=${LOCAL_DB_POSTGRESQL_PASSWORD}
spring.jpa.database-platform=${LOCAL_DB_POSTGRESQL_PLATFORM}
spring.jpa.hibernate.ddl-auto=${LOCAL_DB_POSTGRESQL_HIBERNATE}


#JWT Configurations
jwt.secret.string=${JWT_SECRET}
jwt.expiration.time=${JWT_EXPIRATION_TIME}

